# Basic settings
SEED: 0
RUN_NAME:
DEBUG: true

# Model configuration
MODEL:
  TYPE: mscan
  ENCODER:
    WEIGHTS: /home/myl/image-as-an-imu/checkpoints/mscan_t.pth # Path to the pretrained mscan_b.pth weights
  POSE_HEAD:
    SUPERVISE: false
    USE_PINV: false
    CUT_BORDERS: true

# Training configuration
TRAINING:
  BATCH_SIZE: 32
  NUM_WORKERS: 4
  EPOCHS: 20
  OPTIMIZER: adamw
  LR: 1e-5 # Unused since we use the OneCycleLR scheduler
  LR_SCHEDULER:
    TYPE: onecycle
    MAX_LR: 1e-4  # Maximum learning rate for OneCycleLR
    PCT_START: 0.3  # Percentage of cycle spent increasing LR (default: 30%)
    ANNEAL_STRATEGY: cos  # "cos" or "linear"
    CYCLE_MOMENTUM: true  # Whether to cycle momentum inversely to LR
    BASE_MOMENTUM: 0.85  # Lower momentum bound for cycling
    MAX_MOMENTUM: 0.95  # Upper momentum bound for cycling
    DIV_FACTOR: 25.0  # Initial LR = MAX_LR / DIV_FACTOR
    FINAL_DIV_FACTOR: 10000.0  # Final LR = INITIAL_LR / FINAL_DIV_FACTOR
    THREE_PHASE: false  # If True, use three phase schedule

  MIXED_PRECISION: bf16
  ROT_LOSS_WEIGHT: 1.0
  TRANS_LOSS_WEIGHT: 10.0
  POSE_LOSS_WEIGHT: 1000.0
  FLOW_LOSS_WEIGHT: 1e-4
  DEPTH_LOSS_WEIGHT: 1e-3
  POSE_ONLY: false
  USE_PSEUDO_GT: false

  VAL_FIRST: false
  VAL_INTERVAL: 1

  CHECKPOINT:
    SAVE: true
    RESUME_PATH:
    DIR: /home/myl/image-as-an-imu/checkpoints/mscan_tiny_imu/stage1 # Path to the directory to save checkpoints
    INTERVAL: 5
    OVERWRITE: false

# Dataset configuration
DATASET:
  TRAIN_DATA: /home/myl/image-as-an-imu/synth_data_gen/synth_data_train-skip_10.csv # Path to the training data csv file
  VAL_DATA: /home/myl/image-as-an-imu/synth_data_gen/synth_data_val-skip_10.csv # Path to the validation data csv file
  HEIGHT: 252
  WIDTH: 336
  CENTERCROP_DIMS: [224, 320]
  DATA_AUGMENT:
    - color_transforms
    - noise_transforms

# Logging configuration
LOGGING:
  PLATFORM: wandb # Options: wandb, null
  STEPS_PER_PRINT: 10  # How often to print training progress
  TRAIN_VISUALS_INTERVAL: 1000  # How often to log training visuals, in steps