# Basic settings
SEED: 0
RUN_NAME:
DEBUG: true

# Model configuration
MODEL:
  TYPE: mscan
  ENCODER:
    WEIGHTS: /home/myl/image-as-an-imu/checkpoints/mscan_t.pth
  POSE_HEAD:
    SUPERVISE: true # We use pose supervision in stage 2
    USE_PINV: false
    CUT_BORDERS: true

# Training configuration
TRAINING:
  BATCH_SIZE: 8 # We use a smaller batch size in stage 2 to be able to fit in memory
  NUM_WORKERS: 4
  EPOCHS: 20
  OPTIMIZER: adamw
  LR: 1e-5
  LR_SCHEDULER:
    TYPE: none
    MAX_LR: 1e-4
    PCT_START: 0.3
    ANNEAL_STRATEGY: cos
    CYCLE_MOMENTUM: true
    BASE_MOMENTUM: 0.85
    MAX_MOMENTUM: 0.95
    DIV_FACTOR: 25.0
    FINAL_DIV_FACTOR: 10000.0
    THREE_PHASE: false

  MIXED_PRECISION: bf16
  ROT_LOSS_WEIGHT: 0
  TRANS_LOSS_WEIGHT: 10.0
  POSE_LOSS_WEIGHT: 1000.0
  FLOW_LOSS_WEIGHT: 1e-4
  DEPTH_LOSS_WEIGHT: 1e-3
  POSE_ONLY: false
  USE_PSEUDO_GT: false

  VAL_FIRST: false
  VAL_INTERVAL: 1

  CHECKPOINT:
    SAVE: true
    RESUME_PATH: /home/myl/image-as-an-imu/checkpoints/mscan_tiny/stage1/ckpt_000019 # In stage 2 we resume from the last checkpoint of stage 1
    DIR: /home/myl/image-as-an-imu/checkpoints/mscan_tiny/stage2_imu # Path to the directory to save checkpoints
    INTERVAL: 5
    OVERWRITE: false

# Dataset configuration
DATASET:
  TRAIN_DATA: /home/myl/image-as-an-imu/synth_data_gen/synth_data_train-skip_10_with_imu_rad_per_frame.csv # Path to the training data csv file (same as stage 1)
  VAL_DATA: /home/myl/image-as-an-imu/synth_data_gen/synth_data_val-skip_10_with_imu_rad_per_frame.csv # Path to the validation data csv file (same as stage 1)
  HEIGHT: 252
  WIDTH: 336
  CENTERCROP_DIMS: [224, 320]
  DATA_AUGMENT:
    - color_transforms
    - noise_transforms

# Logging configuration
LOGGING:
  PLATFORM: wandb # Options: wandb, null
  STEPS_PER_PRINT: 10  # How often to print training progress
  TRAIN_VISUALS_INTERVAL: 1000  # How often to log training visuals, in steps