data_path: /home/myl/strayscanner_data # Required path to sequence directory
precomputed_vels_path: null
save_suffix: fps1
save_vels: True
viz_metrics: True

ckpt_path: /home/myl/image-as-an-imu/checkpoints/segnext_iaai.pth